version: "3.9"
services:
  dna-go:
    build: .
    image: dna-analysis-go:dev
    container_name: dna-analysis-go-container
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    restart: always